### ISSUE TITLE
Rendering the emojis is very slow

### ISSUE THREAD

**Issue by akhilmankala** [AniTrend/android-emojify#3]
Hi, 

The library is very good and made my work easy but the only issue is. I have list items in which some of them have emojis when scrolling through emoji list items, the scroll is not working and it is very slow. Can you give any solution to the issue? @wax911

**Comment by wax911** [comment]
Hi @akhilmankala yes if you read through the description you can see I suggested using:
>Html.fromHtml()

The reason for this is to allow the html parser to decode emojis since after they are saved as (html entities) it knows the native representation for the emojis.

So in your list adapter you would do something along the lines of:
```
public void onBindViewHolder(int position) {
    holder.textView.setText(Html.fromHtml(data.get(position).getText());
}
```
